# Generated by Django 4.1.7 on 2023-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_post_title'),
        ('accounts', '0005_remove_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewed_posts',
            field=models.ManyToManyField(related_name='viewers', related_query_name='viewer', to='feed.post'),
        ),
    ]
