# Generated by Django 4.1.7 on 2023-02-23 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField(max_length=15000)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', related_query_name='post', to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(related_name='%(app_label)s_disliked_%(class)s', related_query_name='%(app_label)s_disliked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='%(app_label)s_liked_%(class)s', related_query_name='%(app_label)s_liked_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='posts/%Y/%m/%d/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='feed.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('answer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='feed.comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', related_query_name='comment', to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(related_name='%(app_label)s_disliked_%(class)s', related_query_name='%(app_label)s_disliked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='%(app_label)s_liked_%(class)s', related_query_name='%(app_label)s_liked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='feed.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
