# Generated by Django 4.1.7 on 2023-02-25 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(related_name='%(app_label)s_disliked_%(class)ss', related_query_name='%(app_label)s_disliked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='%(app_label)s_liked_%(class)ss', related_query_name='%(app_label)s_liked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='%(app_label)s_disliked_%(class)ss', related_query_name='%(app_label)s_disliked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='%(app_label)s_liked_%(class)ss', related_query_name='%(app_label)s_liked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
