# Generated by Django 4.1.7 on 2023-03-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_comment_data_update_comment_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
