# Generated by Django 4.1.7 on 2023-03-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_update',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_update',
            new_name='date_update',
        ),
    ]
