# Generated by Django 4.1.7 on 2023-03-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_rename_data_update_comment_date_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_update',
            new_name='data_update',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_update',
            new_name='data_update',
        ),
    ]
